export const WS_FEED_CONNECTION_START: 'WS_FEED_CONNECTION_START' = 'WS_FEED_CONNECTION_START';
export const WS_FEED_CONNECTION_STOP: 'WS_FEED_CONNECTION_STOP' = 'WS_FEED_CONNECTION_STOP';
export const WS_FEED_CONNECTION_SUCCESS: 'WS_FEED_CONNECTION_SUCCESS' = 'WS_FEED_CONNECTION_SUCCESS';
export const WS_FEED_CONNECTION_ERROR: 'WS_FEED_CONNECTION_ERROR' = 'WS_FEED_CONNECTION_ERROR';
export const WS_FEED_CONNECTION_CLOSED: 'WS_FEED_CONNECTION_CLOSED' = 'WS_FEED_CONNECTION_CLOSED';
export const WS_FEED_GET_MESSAGE: 'WS_FEED_GET_MESSAGE' = 'WS_FEED_GET_MESSAGE';
export const WS_FEED_SEND_MESSAGE: 'WS_FEED_SEND_MESSAGE' = 'WS_FEED_SEND_MESSAGE';

export type TWsFeedMiddlewareActions = {
  readonly wsConnect: typeof WS_FEED_CONNECTION_START;
  readonly wsSendMessage: typeof WS_FEED_SEND_MESSAGE;
  readonly wsDisconnect: typeof WS_FEED_CONNECTION_STOP;
  readonly onOpen: typeof WS_FEED_CONNECTION_SUCCESS;
  readonly onClose: typeof WS_FEED_CONNECTION_CLOSED;
  readonly onError: typeof WS_FEED_CONNECTION_ERROR;
  readonly onMessage: typeof WS_FEED_GET_MESSAGE;
};

export const wsFeedActions: TWsFeedMiddlewareActions = {
  wsConnect: WS_FEED_CONNECTION_START,
  wsSendMessage: WS_FEED_SEND_MESSAGE,
  wsDisconnect: WS_FEED_CONNECTION_STOP,
  onOpen: WS_FEED_CONNECTION_SUCCESS,
  onClose: WS_FEED_CONNECTION_CLOSED,
  onError: WS_FEED_CONNECTION_ERROR,
  onMessage: WS_FEED_GET_MESSAGE
};